name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          venv/bin/pytest

      - name: Check test results
        if: failure()
        run: echo "❌ Tests failed. Fix errors before merging."

      - name: Success message
        if: success()
        run: echo "✅ All tests passed! Ready to merge."
